class AppLanguage {
  final String name;
  final String code;
  final String flag;

  const AppLanguage(this.name, this.code, this.flag);
}

class AppLanguages {
  static const List<AppLanguage> all = [
    AppLanguage('Afaan Oromo', 'om', '🇴🇲'),
    AppLanguage('Afrikaans', 'af', '🇦🇫'),
    AppLanguage('Akan / Twi', 'ak', '🇦🇰'),
    AppLanguage('Albanian', 'sq', '🇸🇶'),
    AppLanguage('Amharic', 'am', '🇦🇲'),
    AppLanguage('Arabic (Algerian)', 'ar-DZ', '🇩🇿'),
    AppLanguage('Arabic (Egyptian)', 'ar-EG', '🇪🇬'),
    AppLanguage('Arabic (Gulf)', 'ar-AE', '🇦🇪'),
    AppLanguage('Arabic (Iraqi)', 'ar-IQ', '🇮🇶'),
    AppLanguage('Arabic (Levantine)', 'ar-LB', '🇱🇧'),
    AppLanguage('Arabic (Maghrebi)', 'ar-MA', '🇲🇦'),
    AppLanguage('Arabic (Modern Standard)', 'ar', '🇦🇷'),
    AppLanguage('Arabic (Sudanese)', 'ar-SD', '🇸🇩'),
    AppLanguage('Arabic (Yemeni)', 'ar-YE', '🇾🇪'),
    AppLanguage('Armenian', 'hy', '🇭🇾'),
    AppLanguage('Assamese', 'as', '🇦🇸'),
    AppLanguage('Asturian', 'ast', '🇪🇸'),
    AppLanguage('Aymara', 'ay', '🇦🇾'),
    AppLanguage('Awadhi', 'awa', '🇮🇳'),
    AppLanguage('Azerbaijani', 'az', '🇦🇿'),
    AppLanguage('Bambara', 'bm', '🇧🇲'),
    AppLanguage('Basque', 'eu', '🇪🇺'),
    AppLanguage('Belarusian', 'be', '🇧🇪'),
    AppLanguage('Bengali', 'bn', '🇧🇳'),
    AppLanguage('Bhojpuri', 'bho', '🇮🇳'),
    AppLanguage('Bodo', 'brx', '🇮🇳'),
    AppLanguage('Bosnian', 'bs', '🇧🇸'),
    AppLanguage('Brahui', 'brh', '🇵🇰'),
    AppLanguage('Breton', 'br', '🇧🇷'),
    AppLanguage('Bulgarian', 'bg', '🇧🇬'),
    AppLanguage('Burmese (Myanmar)', 'my', '🇲🇾'),
    AppLanguage('Cantonese', 'yue', '🇭🇰'),
    AppLanguage('Catalan', 'ca', '🇨🇦'),
    AppLanguage('Cebuano', 'ceb', '🇵🇭'),
    AppLanguage('Chadian Arabic', 'shu', '🇹🇩'),
    AppLanguage('Chhattisgarhi', 'hne', '🇮🇳'),
    AppLanguage('Chichewa / Chewa', 'ny', '🇳🇾'),
    AppLanguage('Chinese (Simplified)', 'zh-CN', '🇨🇳'),
    AppLanguage('Chinese (Traditional)', 'zh-TW', '🇹🇼'),
    AppLanguage('Corsican', 'co', '🇨🇴'),
    AppLanguage('Croatian', 'hr', '🇭🇷'),
    AppLanguage('Czech', 'cs', '🇨🇸'),
    AppLanguage('Danish', 'da', '🇩🇦'),
    AppLanguage('Dogri', 'doi', '🇮🇳'),
    AppLanguage('Dutch', 'nl', '🇳🇱'),
    AppLanguage('English (UK)', 'en-GB', '🇬🇧'),
    AppLanguage('English (US)', 'en-US', '🇺🇸'),
    AppLanguage('Esperanto', 'eo', '🇪🇴'),
    AppLanguage('Estonian', 'et', '🇪🇹'),
    AppLanguage('Ewe', 'ee', '🇪🇪'),
    AppLanguage('Fang', 'fan', '🇬🇶'),
    AppLanguage('Faroese', 'fo', '🇫🇴'),
    AppLanguage('Filipino / Tagalog', 'fil', '🇵🇭'),
    AppLanguage('Finnish', 'fi', '🇫🇮'),
    AppLanguage('French', 'fr', '🇫🇷'),
    AppLanguage('French (Canada)', 'fr-CA', '🇨🇦'),
    AppLanguage('Frisian', 'fy', '🇫🇾'),
    AppLanguage('Fulani / Fula', 'ff', '🇫🇫'),
    AppLanguage('Gan Chinese', 'gan', '🇨🇳'),
    AppLanguage('Galician', 'gl', '🇬🇱'),
    AppLanguage('Georgian', 'ka', '🇰🇦'),
    AppLanguage('German', 'de', '🇩🇪'),
    AppLanguage('Greek', 'el', '🇪🇱'),
    AppLanguage('Guarani', 'gn', '🇬🇳'),
    AppLanguage('Gujarati', 'gu', '🇬🇺'),
    AppLanguage('Hakka', 'hak', '🇨🇳'),
    AppLanguage('Haitian Creole', 'ht', '🇭🇹'),
    AppLanguage('Haryanvi', 'bgc', '🇮🇳'),
    AppLanguage('Hausa', 'ha', '🇭🇦'),
    AppLanguage('Hebrew', 'he', '🇭🇪'),
    AppLanguage('Hindi', 'hi', '🇭🇮'),
    AppLanguage('Hiligaynon', 'hil', '🇵🇭'),
    AppLanguage('Hmong', 'hmn', '🇨🇳'),
    AppLanguage('Hungarian', 'hu', '🇭🇺'),
    AppLanguage('Icelandic', 'is', '🇮🇸'),
    AppLanguage('Igbo', 'ig', '🇮🇬'),
    AppLanguage('Ilocano', 'ilo', '🇵🇭'),
    AppLanguage('Indonesian', 'id', '🇮🇩'),
    AppLanguage('Irish (Gaeilge)', 'ga', '🇬🇦'),
    AppLanguage('isiXhosa', 'xh', '🇽🇭'),
    AppLanguage('Italian', 'it', '🇮🇹'),
    AppLanguage('Japanese', 'ja', '🇯🇦'),
    AppLanguage('Javanese', 'jv', '🇯🇻'),
    AppLanguage('Kabyle (Algerian Berber)', 'kab', '🇩🇿'),
    AppLanguage('Kannada', 'kn', '🇰🇳'),
    AppLanguage('Kanuri', 'kr', '🇰🇷'),
    AppLanguage('Kashmiri', 'ks', '🇰🇸'),
    AppLanguage('Kazakh', 'kk', '🇰🇰'),
    AppLanguage('Khmer', 'km', '🇰🇲'),
    AppLanguage('Khasi', 'kha', '🇮🇳'),
    AppLanguage('Kikuyu', 'ki', '🇰🇮'),
    AppLanguage('Kinyarwanda', 'rw', '🇷🇼'),
    AppLanguage('Kirundi', 'rn', '🇷🇳'),
    AppLanguage('Kongo', 'kg', '🇰🇬'),
    AppLanguage('Konkani', 'kok', '🇮🇳'),
    AppLanguage('Korean', 'ko', '🇰🇴'),
    AppLanguage('Krio (Sierra Leone)', 'kri', '🇸🇱'),
    AppLanguage('Kurdish', 'ku', '🇰🇺'),
    AppLanguage('Kurmanji (Northern Kurdish)', 'kmr', '🇹🇷'),
    AppLanguage('Kyrgyz', 'ky', '🇰🇾'),
    AppLanguage('Lao', 'lo', '🇱🇴'),
    AppLanguage('Latin', 'la', '🇱🇦'),
    AppLanguage('Latvian', 'lv', '🇱🇻'),
    AppLanguage('Lingala', 'ln', '🇱🇳'),
    AppLanguage('Lithuanian', 'lt', '🇱🇹'),
    AppLanguage('Luba-Katanga', 'lu', '🇱🇺'),
    AppLanguage('Luganda (Ganda)', 'lg', '🇱🇬'),
    AppLanguage('Luxembourgish', 'lb', '🇱🇧'),
    AppLanguage('Macedonian', 'mk', '🇲🇰'),
    AppLanguage('Magahi', 'mag', '🇮🇳'),
    AppLanguage('Malagasy', 'mg', '🇲🇬'),
    AppLanguage('Maithili', 'mai', '🇮🇳'),
    AppLanguage('Malay', 'ms', '🇲🇸'),
    AppLanguage('Malayalam', 'ml', '🇲🇱'),
    AppLanguage('Maltese', 'mt', '🇲🇹'),
    AppLanguage('Manipuri (Meitei)', 'mni', '🇮🇳'),
    AppLanguage('Marathi', 'mr', '🇲🇷'),
    AppLanguage('Marwari', 'mwr', '🇮🇳'),
    AppLanguage('Māori', 'mi', '🇲🇮'),
    AppLanguage('Min Nan / Hokkien', 'nan', '🇹🇼'),
    AppLanguage('Mongolian', 'mn', '🇲🇳'),
    AppLanguage('Montenegrin', 'sr-ME', '🇲🇪'),
    AppLanguage('Mizo', 'lus', '🇮🇳'),
    AppLanguage('Nepali', 'ne', '🇳🇪'),
    AppLanguage('Norwegian Bokmål', 'nb-NO', '🇳🇴'),
    AppLanguage('Norwegian Nynorsk', 'nn-NO', '🇳🇴'),
    AppLanguage('Occitan', 'oc', '🇴🇨'),
    AppLanguage('Odia (Oriya)', 'or', '🇴🇷'),
    AppLanguage('Pashto', 'ps', '🇵🇸'),
    AppLanguage('Persian / Farsi', 'fa', '🇫🇦'),
    AppLanguage('Polish', 'pl', '🇵🇱'),
    AppLanguage('Portuguese (Brazil)', 'pt-BR', '🇧🇷'),
    AppLanguage('Portuguese (Portugal)', 'pt-PT', '🇵🇹'),
    AppLanguage('Punjabi', 'pa', '🇵🇦'),
    AppLanguage('Quechua (Standard)', 'qu', '🇶🇺'),
    AppLanguage('Rajasthani', 'raj', '🇮🇳'),
    AppLanguage('Romanian', 'ro', '🇷🇴'),
    AppLanguage('Romansh', 'rm', '🇷🇲'),
    AppLanguage('Russian', 'ru', '🇷🇺'),
    AppLanguage('Samoan', 'sm', '🇸🇲'),
    AppLanguage('Sanskrit', 'sa', '🇸🇦'),
    AppLanguage('Santali', 'sat', '🇮🇳'),
    AppLanguage('Saraiki', 'skr', '🇵🇰'),
    AppLanguage('Scottish Gaelic', 'gd', '🇬🇩'),
    AppLanguage('Serbian', 'sr', '🇸🇷'),
    AppLanguage('Sesotho', 'st', '🇸🇹'),
    AppLanguage('Setswana', 'tn', '🇹🇳'),
    AppLanguage('Shona', 'sn', '🇸🇳'),
    AppLanguage('Sicilian', 'scn', '🇮🇹'),
    AppLanguage('Sindhi', 'sd', '🇸🇩'),
    AppLanguage('Sinhala', 'si', '🇸🇮'),
    AppLanguage('Slovak', 'sk', '🇸🇰'),
    AppLanguage('Slovenian', 'sl', '🇸🇱'),
    AppLanguage('Somali', 'so', '🇸🇴'),
    AppLanguage('Spanish (Latin America / Mexico)', 'es-MX', '🇲🇽'),
    AppLanguage('Spanish (Spain)', 'es-ES', '🇪🇸'),
    AppLanguage('Sundanese', 'su', '🇸🇺'),
    AppLanguage('Swahili', 'sw', '🇸🇼'),
    AppLanguage('Swedish', 'sv', '🇸🇻'),
    AppLanguage('Tajik', 'tg', '🇹🇬'),
    AppLanguage('Tamazight (Standard Moroccan Berber)', 'zgh', '🇲🇦'),
    AppLanguage('Tamil', 'ta', '🇹🇦'),
    AppLanguage('Tatar', 'tt', '🇹🇹'),
    AppLanguage('Telugu', 'te', '🇹🇪'),
    AppLanguage('Thai', 'th', '🇹🇭'),
    AppLanguage('Tigrinya', 'ti', '🇹🇮'),
    AppLanguage('Tok Pisin', 'tpi', '🇵🇬'),
    AppLanguage('Tongan', 'to', '🇹🇴'),
    AppLanguage('Tulu', 'tcy', '🇮🇳'),
    AppLanguage('Turkish', 'tr', '🇹🇷'),
    AppLanguage('Ukrainian', 'uk', '🇺🇰'),
    AppLanguage('Urdu', 'ur', '🇺🇷'),
    AppLanguage('Uyghur', 'ug', '🇺🇬'),
    AppLanguage('Uzbek', 'uz', '🇺🇿'),
    AppLanguage('Venetian', 'vec', '🇮🇹'),
    AppLanguage('Vietnamese', 'vi', '🇻🇮'),
    AppLanguage('Waray', 'war', '🇵🇭'),
    AppLanguage('Welsh', 'cy', '🇨🇾'),
    AppLanguage('Wolof', 'wo', '🇼🇴'),
    AppLanguage('Wu Chinese (Shanghainese)', 'wuu', '🇨🇳'),
    AppLanguage('Xiang Chinese', 'hsn', '🇨🇳'),
    AppLanguage('Xitsonga', 'ts', '🇹🇸'),
    AppLanguage('Yiddish', 'yi', '🇾🇮'),
    AppLanguage('Yoruba', 'yo', '🇾🇴'),
    AppLanguage('Zulu', 'zu', '🇿🇺'),
  ];
}
